### ISSUE TITLE
error with message: 'The model: `gpt-4` does not exist'

### ISSUE THREAD

**Issue by troy-lamerton** [neebs12/Search-across-knowledge-bases-with-Langchain-and-OpenAI#6]
I have followed the README and set the models to use `"gpt-3.5-turbo"`
When I search for `gpt-4` string, I only see it in comments, so this error is strange.

```js
response: {
    ok: false,
    status: 404,
    statusText: 'Not Found',
    
    // [...]
    data: {
      error: {
        message: 'The model: `gpt-4` does not exist',
        type: 'invalid_request_error',
        param: null,
        code: 'model_not_found'
      }
    }
}
```

Do you know how to fix this? I don't have access to gpt-4 with my api key

**Comment by neebs12** [comment]
hmmm, your best bet is to look for all the `modelName` arguments and manually set them to "gpt-3.5-turbo". For the most part, all of them should have defaulted to 3.5 anyway.

like so: 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/51255216/232560529-d7174b87-938f-4449-a621-99bdfaa5f6a0.png">

Nevertheless, create a `.env` file inside your `/backend` folder and lets see how it goes - replace all "gpt-4" with "gpt-3.5-turbo"
```
OPENAI_API_KEY=

# switch to "gpt-3.5-turbo" if you dont have access, but app may not contextualize as well
QUESTION_REFINER_AGENT_MODEL_NAME="gpt-4"
# "gpt-3.5-turbo" is sufficient but "gpt-4" will provide higher quality final answers
AGGREGATOR_STREAM_AGENT_MODEL_NAME="gpt-4"
```

**Comment by troy-lamerton** [comment]
yep I checked those.
Seems like a bug on openai's end?

**Comment by troy-lamerton** [comment]
woops, my VSCode didnt save the updated env - its working good now!
